# https://docs.gitlab.com/ee/ci/yaml/
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# https://gitsc.emundo.eu/ci/lint
# https://gitsc.emundo.eu/help/ci/README.md

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG

default:
  image: eu.gcr.io/emundo-gke-test/emundo/docker-compose-openjdk-node-gradle:openjdk-11-gradle-6
  cache:
    paths:
      - .gradle
  interruptible: true

variables:
  # https://docs.gitlab.com/ee/ci/large_repositories/
  GIT_DEPTH: 10
  # https://docs.gradle.org/current/userguide/build_cache.html
  # https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:why_the_daemon
  JAVA_OPTS: "-Xmx4096m -Dorg.gradle.caching=true -Dorg.gradle.daemon=false"
  # https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
  GRADLE_USER_HOME: ${CI_PROJECT_DIR}/.gradle

stages:
  - build
  - image
  - smoke

.job:
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
      - job_execution_timeout
      - stuck_or_timeout_failure

.build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/docker

dev:build:
  extends:
    - .job
    - .build
  rules:
    - if: $CI_MERGE_REQUEST_ID
      
.image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - test -z "${IMAGE_NAME}" && exit 1
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context build/docker --dockerfile build/docker/Dockerfile --destination ${IMAGE_NAME}

dev:image:
  extends:
    - .job
    - .image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  rules:
    - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TITLE !~ /^WIP:/
    - if: $CI_MERGE_REQUEST_ID
      when: manual      
      allow_failure: true

tag:image:
  extends:
    - .job
    - .image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

.smoke:
  image:
    name: ${IMAGE_NAME}
    entrypoint: [""]
  stage: smoke
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - /entrypoint.sh atlas-version

dev:smoke:
  extends:
    - .job
    - .smoke
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  rules:
    - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TITLE !~ /^WIP:/
    - if: $CI_MERGE_REQUEST_ID
      when: manual      
      allow_failure: true

tag:smoke:
  extends:
    - .job
    - .smoke
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
