# https://docs.gitlab.com/ce/ci/yaml/
# https://gitsc.emundo.eu/ci/lint
# https://gitsc.emundo.eu/help/ci/README.md

image: emundo/docker-compose-openjdk-node-gradle:openjdk-8-gradle-5.4

variables:
  # https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:why_the_daemon
  JAVA_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false"

stages:
  - build
  - docker_push
  - docker_run
  - publish

cache:
  paths:
    - .gradle

before_script:
  # Gradle-Ressourcen im job-übergreifenden Cache
  - export GRADLE_USER_HOME=${PWD}/.gradle

build:
  stage: build
  script:
    - gradle build --info
  artifacts:
    expire_in: 1 hour
    name: "$CI_PROJECT_PATH_SLUG-snapshot"
    paths:
      - build/docker

docker_push_dev:
  stage: docker_push
  except:
    - master
    - tags
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:snapshot" build/docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE:snapshot"

docker_run_dev:
  image:
    name: $CI_REGISTRY_IMAGE:snapshot
    entrypoint: [""]
  stage: docker_run
  except:
    - master
    - tags
  script:
    - atlas-version

publish:
  stage: publish
  only:
    - master
    - tags
  script:
    - test -z $CI_COMMIT_TAG && tag=latest || tag=$CI_COMMIT_TAG
    - docker build -t "$CI_REGISTRY_IMAGE:$tag" build/docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE:$tag"
